run_mode: kSim
trigger_mode: kManual
world_frame_id: uav1/fixed_origin
robot_type: kAerial
output_type: kTopic
init_motion_enable: false
planner_trigger_lead_time: 0.4
smooth_heading_enable: true
init_motion:
  z_takeoff: .2
  z_drop: .3
  x_forward: 1.0

# Group related parameters to be shared between nodes.
RobotDynamics:
  v_max: 1.0
  v_init_max: 1.0
  v_homing_max: 1.0
  yaw_rate_max: 0.15
  dt: 0.05
